import Link from "next/link";
import { Nav } from "@/components/Nav";

export default function JudgesPage() {
  return (
    <div className="page">
      <Nav current="judges" />

      <header className="doc-header">
        <h1>Judge Verification Guide</h1>
        <p className="doc-subtitle">Congressional App Challenge 2026 — Haloscan</p>
        <p className="doc-meta">
          This page describes how to verify Haloscan in approximately 90 seconds. The project addresses the
          diagnostic gap left open by Reese&apos;s Law (P.L. 117-171): Congress mandated safer battery packaging,
          but emergency departments still struggle to distinguish batteries from coins on X-ray.
        </p>
      </header>

      <section>
        <h2>1. Quick Verification Protocol</h2>
        <ol className="research">
          <li>
            Open the{" "}
            <Link href="/scan">Clinical Scanner</Link> and press key <strong>1</strong> (button battery case).
            Confirm a CRITICAL protocol appears with the two-hour esophageal window.
          </li>
          <li>
            Press key <strong>3</strong> (stacked coins — the hard false-halo case). Confirm the system flags a
            battery emergency despite coin-like appearance.
          </li>
          <li>Scroll to Grad-CAM, detection overlay, and radial intensity profile figures.</li>
          <li>
            Clone the repository and run <code>python3 tests/smoke_test.py</code> — all checks should pass.
          </li>
          <li>
            Review <Link href="/gallery">figure gallery</Link>,{" "}
            <Link href="/methodology">methodology</Link>,{" "}
            <Link href="/architecture">architecture</Link>,{" "}
            <Link href="/validation">validation figures</Link>, and{" "}
            <Link href="/use-cases">clinical use cases</Link> on the site; README.md and TECHNICAL.md on GitHub.
          </li>
        </ol>
      </section>

      <section>
        <h2>2. Rubric Mapping</h2>

        <h3>2.1 Problem &amp; Idea</h3>
        <p>
          Reese&apos;s Law fixed prevention; Haloscan addresses diagnosis. The app targets a named clinical
          failure mode (stacked coins mimicking the double halo sign) and the two-hour esophageal emergency
          window for lodged button batteries.
        </p>

        <h3>2.2 Implementation</h3>
        <p>
          Live web demo with real PyTorch inference (not pre-recorded JSON). Dual-view upload, ensemble
          probability breakdown, Grad-CAM explainability, printable HTML clinical reports, and deployment on
          Vercel (frontend) plus Render (API).
        </p>

        <h3>2.3 Technical Depth</h3>
        <p>
          OpenCV radial halo physics combined with DualViewNet fusion. Kaggle CPU training with bundled weights.
          Automated smoke tests. Open-source MIT license. Battery sensitivity exceeds the published Emory 2020
          machine-learning baseline on synthetic holdout data.
        </p>
      </section>

      <section>
        <h2>3. Site Map for Judges</h2>
        <table className="data">
          <thead>
            <tr>
              <th>Page</th>
              <th>What to verify</th>
            </tr>
          </thead>
          <tbody>
            {[
              ["/scan", "Live PyTorch inference, keys 1–4, Grad-CAM + radial charts"],
              ["/gallery", "All 16+ exported figure panels with inference metrics"],
              ["/validation", "Benchmark chart, confusion matrix, 5/5 smoke tests"],
              ["/methodology", "Synthetic training data, radial profiles, decision flow"],
              ["/architecture", "SVG pipeline diagram, API routes, deployment"],
              ["/use-cases", "Four clinical vignettes with real model outputs"],
            ].map(([href, desc]) => (
              <tr key={href}>
                <td>
                  <Link href={href}>{href}</Link>
                </td>
                <td>{desc}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <section>
        <h2>4. Published Figures on the Home Page</h2>
        <p>
          The landing page includes Figures 1–3 generated by the same inference pipeline as the live scanner:
          AP radiographs, detection overlays, Grad-CAM attention maps, and radial intensity profiles. These
          are exported via <code>python3 scripts/export_figures.py</code> and stored in{" "}
          <code>website/public/figures/</code>.
        </p>
      </section>

      <section>
        <h2>5. Key Repository Files</h2>
        <ul className="list">
          {[
            ["haloscan/halo_analyzer.py", "Radial halo profiling"],
            ["haloscan/models.py", "DualViewNet architecture"],
            ["haloscan/inference.py", "Ensemble engine and Grad-CAM"],
            ["haloscan/clinical.py", "Protocol engine (CRITICAL / URGENT / ROUTINE)"],
            ["weights/haloscan.pt", "Bundled model weights (~3.5 MB)"],
            ["tests/smoke_test.py", "Automated verification"],
          ].map(([file, desc]) => (
            <li key={file}>
              <a
                href={`https://github.com/arjunkshah12345-hash/haloscan/blob/main/${file}`}
                className="row-link"
                target="_blank"
                rel="noopener noreferrer"
              >
                <span>
                  <code>{file}</code> — {desc}
                </span>
                <span>↗</span>
              </a>
            </li>
          ))}
        </ul>
      </section>

      <footer>
        <span>Not a medical device · No patient data stored</span>
        <Link href="/">← Home</Link>
      </footer>
    </div>
  );
}
